### DISCUSSION TITLE
Export global environment variables to github actions with mage

### DISCUSSION THREAD

**Discussion by iancardosozup** [magefile/mage#389] [Q&A] [answered]
I'm currently working on [horusec](https://github.com/ZupIT/horusec) using mage and trying to export environment variables to my action pipeline, but it's not working. Using github [set environments variables documentation](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable) i was able to reproduce it.
![image](https://user-images.githubusercontent.com/86669442/142682488-4b39d180-2f84-48fb-b127-3b1014b7265a.png)
but when i try it with mage, i can't.
![image](https://user-images.githubusercontent.com/86669442/142682724-d94c0bc0-2dfa-4191-860e-4d4834f3dd14.png)
and here it's my mage function 

```
func SetPotatoVariable() error {
	println("echo potato=fried_potato >> $GITHUB_ENV ")
	fmt.Println("echo potato=fried_potato >> $GITHUB_ENV ")
	return sh.Run("echo", "potato=fried_potato", ">>", "$GITHUB_ENV")
}

```
and my actions step 
```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install Mage
        run: go install github.com/magefile/mage@v1.11
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
      - name: Set the value
        id: set_potato
        run: |
          mage -v setPotatoVariable
      - name: Use the value
        id: use_potato
        run: |
          echo "${{ env.potato }}" # This will output 'fried_potato'
```
Anyone knows the reason why it's happening?

anyway this project is amazing, keep up with the good job

###EDIT

i found a solution by using the [output feature](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) for github actions if someone needs it, you can check on [horusec-devkit](https://github.com/ZupIT/horusec-devkit/blob/44f0135574843da471ccdd05c058272533318e0e/pkg/utils/mageutils/version.go#L208) with another mage functions.
